// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// CompatAccessTokenAuth provides CompatAccessTokenAuth security value.
	// コントロールパネルアクセストークン認証
	// - ユーザ名にアクセスモード（M-G、M-A、U-G、U-A）を指定
	// - パスワードに発行したアクセストークンを指定.
	CompatAccessTokenAuth(ctx context.Context, operationName OperationName) (CompatAccessTokenAuth, error)
}

func (s *Client) securityCompatAccessTokenAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CompatAccessTokenAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CompatAccessTokenAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
