// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *AuthConditionsIPRestriction) setDefaults() {
	{
		val := AuthConditionsIPRestrictionMode("allow_all")
		s.Mode = val
	}
}

// setDefaults set default value of fields.
func (s *Folder) setDefaults() {
	{
		s.ParentID.Null = true
	}
}

// setDefaults set default value of fields.
func (s *FoldersPostReq) setDefaults() {
	{
		s.ParentID.Null = true
	}
}
